### ISSUE TITLE
graphs not chronological

### ISSUE THREAD

**Issue by mmmries** [film42/cs478-stock-prediction#1]
You're probably already aware of this, but in case it got missed in the mad rush of finishing an awesome project, the labels on your graphs are not chronologically sorted, which makes it really hard to read the graphs.

I think you just need an `order` clause in your `StockPrice` and `Prediction` models

![screen shot 2015-04-06 at 3 13 39 am](https://cloud.githubusercontent.com/assets/80008/7002630/1492cb24-dc0b-11e4-96f8-a77dc11d5ff3.png)

**Comment by film42** [comment]
Thanks for pointing that out! I'll fix it tomorrow!

**Comment by mmmries** [comment]
Sorry for the 2:30am posting. This is what I do to keep myself sane when I wake up in the middle of the night to feed the baby.

**Comment by film42** [comment]
Fixed. But this project has gone the way of the road. https://www.youtube.com/watch?v=3SpihGKmYgY (language warning).
